// This file will be generated by the SDK generation script
// For now, it's a placeholder to ensure the directory structure exists

export interface IRSSpec {
  notional: number;
  ccy: string;
  payFixed: boolean;
  fixedRate?: number;
  floatIndex: string;
  effective: string;
  maturity: string;
  dcFixed: string;
  dcFloat: string;
  freqFixed: string;
  freqFloat: string;
  calendar: string;
  bdc: string;
  csa?: string;
}

export interface CCSSpec {
  notional: number;
  ccy: string;
  payFixed: boolean;
  fixedRate?: number;
  floatIndex: string;
  effective: string;
  maturity: string;
  dcFixed: string;
  dcFloat: string;
  freqFixed: string;
  freqFloat: string;
  calendar: string;
  bdc: string;
  csa?: string;
  notionalCcy2: number;
  ccy2: string;
  fxRate?: number;
}

export interface RunRequest {
  spec: IRSSpec | CCSSpec;
  asOf: string;
  marketDataProfile: string;
  approach: string[];
}

export interface RunStatus {
  id: string;
  status: string;
  created_at: string;
  updated_at: string;
  request: RunRequest;
  error_message?: string;
}

export interface PVBreakdown {
  run_id: string;
  total_pv: number;
  components: Record<string, number>;
  market_data_hash: string;
  model_hash: string;
  calculated_at: string;
  metadata: Record<string, any>;
}
