name: Deploy Backend to Azure Static Web Apps

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements-azure.txt

      - name: Build And Deploy Backend
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Backend source code path (root of backend repo)
          api_location: "/azure-functions" # Azure Functions path
          output_location: "" # No build output needed for Python
          app_build_command: "echo 'No build step needed for Python backend'"
          api_build_command: "pip install -r requirements-azure.txt"
        env:
          # Environment variables for the backend
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
          POC_ENABLE_IFRS: true
          POC_ENABLE_PARSE: true
          POC_ENABLE_EXPLAIN: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
